ante/fee.go, ante/fee_test.go, ante/handler_options.go, app/app.go, app/cli/config_test.go, server/config/config.go, types/flags.go
* bypass-min-fee.msg-max-gas-usage
=> feat: configurable bypass-min-fee maxGas

.github/workflows/codeql-analysis.yml, .github/workflows/security.yml
=> build(deps): bump github/codeql-action from 2 to 3

.github/workflows/release.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml
=> build(deps): bump actions/setup-go from 4 to 5

.github/workflows/lint_golang.yml
=> build(deps): bump golangci/golangci-lint-action from 3 to 4

.github/workflows/docker-push.yml
=> build(deps): bump docker/build-push-action from 4 to 5

.github/workflows/docker-push.yml
=> build(deps): bump docker/metadata-action from 4 to 5

.github/workflows/docker-push.yml
=> build(deps): bump docker/setup-buildx-action from 2 to 3

.github/workflows/docker-push.yml
=> build(deps): bump docker/setup-qemu-action from 2 to 3

.github/workflows/docker-push.yml
=> build(deps): bump docker/login-action from 2 to 3

.github/workflows/solhint.yml
=> build(deps): bump actions/setup-node from 3 to 4

solidity/upgrade.md
=> docs: upgrade bridge contract doc

x/crosschain/keeper/abci_test.go, x/crosschain/keeper/msg_server_test.go
Co-authored-by: nulnut <151493716+nulnut@users.noreply.github.com>
=> test: fix crosschain msg test

solidity/package.json
Ref: https://github.com/functionx/fx-core/pull/zakir/npm
=> chore(504): change @functionx_io/contracts version to v0.2.1

cmd/doctor.go, cmd/doctor_test.go
Ref: https://github.com/functionx/fx-core/pull/zakir/doctor-test
=> test(512): check version compatibility

solidity/tasks/bridge_tasks.ts, solidity/test/bridge_call.ts, solidity/test/common.ts, solidity/test/submit_bridge_call.ts
Ref: https://github.com/functionx/fx-core/pull/nulnut/fix-solidity-format
=> perf(515): solidity typescript

x/crosschain/types/msgs_test.go
Ref: https://github.com/functionx/fx-core/pull/zakir/addr-test
=> test(531): fix validate bech32 refund address

.github/workflows/release.yml
Ref: https://github.com/functionx/fx-core/pull/zakir/release2
=> chore(538): add permissions to release workflows

Makefile, cosmovisor_lite.Dockerfile
Ref: https://github.com/functionx/fx-core/pull/zakir/version
=> chore(541): remove branch name from version

types/version.go
Ref: https://github.com/functionx/fx-core/pull/fx0x55/height
=> refactor(538): update upgrade height

x/gov/keeper/msg_server_test.go, x/gov/types/msgs.go, x/gov/types/msgs_test.go
Ref: https://github.com/functionx/fx-core/pull/nulnut/fix-update-store
=> fix(563): update store key value

x/crosschain/types/codec.go, x/crosschain/types/msgs.go
Ref: https://github.com/functionx/fx-core/pull/fx0x55/fix-cancal-pending-bridgecall
=> fix(567): error and codec

x/crosschain/tests/msg_server_test.go, x/crosschain/types/msgs.go, x/crosschain/types/msgs_test.go, x/crosschain/types/types.go
Ref: https://github.com/functionx/fx-core/pull/fx0x55/fix-add-rewards
=> fix(570): msg validator

cosmovisor.Dockerfile, cosmovisor_lite.Dockerfile
Ref: https://github.com/functionx/fx-core/pull/nulnut/fix-release
=> fix(631): Dockerfile

x/staking/types/contract.go
Ref: https://github.com/functionx/fx-core/pull/nulnut/fix-validator-list
=> fix(657): remove redundant check

testutil/helpers/suite.go, x/crosschain/keeper/many_to_one_test.go
Ref: https://github.com/PundiAi/fx-core/pull/nulnut/fix-test
=> fix(705): rename and refactor

x/crosschain/precompile/contract_test.go
Ref: https://github.com/PundiAi/fx-core/pull/precompile
=> fix(712): set default value for GenerateModuleName

testutil/helpers/suite.go, x/crosschain/keeper/bridge_call_in.go, x/crosschain/keeper/bridge_call_in_test.go
Ref: https://github.com/PundiAi/fx-core/pull/nulnut/fix-refactor-bridgecall
=> fix(717): rename variables and check test token length

contract/IBridgeFeeQuote.go, contract/compile.sh, solidity/contracts/bridge/BridgeFeeOracle.sol, solidity/contracts/bridge/BridgeFeeQuote.sol, solidity/test/bridge_fee_quote.ts
Ref: https://github.com/PundiAi/fx-core/pull/todd/bridge-fee-fix
=> fix(734): update parameter names and references

app/upgrade_test.go, app/upgrades/v8/upgrade.go
Ref: https://github.com/PundiAi/fx-core/pull/fx0x55/defer
=> fix(737): avoid using defer statements inside loops

app/keepers/keepers.go, app/modules.go
Ref: https://github.com/PundiAi/fx-core/pull/zakir/lint
=> chore(750): run linter

solidity/contracts/bridge/BridgeFeeQuote.sol
Ref: https://github.com/PundiAi/fx-core/pull/todd/fix-quote
=> fix(763): corrects calculation of maxQuoteIndex to prevent overflow error

Dockerfile, cosmovisor.Dockerfile, cosmovisor_lite.Dockerfile
Ref: https://github.com/PundiAi/fx-core/pull/770
=> fix: resolve dependency issue during Dockerfile compilation

x/crosschain/migrations/v8/migrate.go
Ref: https://github.com/PundiAi/fx-core/pull/773
=> fix: remove deprecated block key

contract/erc20_token.go
Ref: https://github.com/PundiAi/fx-core/pull/775
=> fix: handle error return

x/staking/precompile/delegate_test.go, x/staking/precompile/undelegate_test.go
Ref: https://github.com/PundiAi/fx-core/pull/792
=> chore: correct typos in test

x/staking/precompile/allowance_shares.go, x/staking/precompile/allowance_shares_test.go, x/staking/precompile/approve_shares_test.go, x/staking/precompile/contract_test.go, x/staking/precompile/delegate_test.go, x/staking/precompile/delegation.go, x/staking/precompile/delegation_rewards.go, x/staking/precompile/delegation_rewards_test.go, x/staking/precompile/delegation_test.go, x/staking/precompile/keeper.go, x/staking/precompile/redelegate.go, x/staking/precompile/redelegate_test.go, x/staking/precompile/slashing_info.go, x/staking/precompile/slashing_info_test.go, x/staking/precompile/transfer_shares_test.go, x/staking/precompile/undelegate_test.go, x/staking/precompile/validator_list.go, x/staking/precompile/validator_list_test.go, x/staking/precompile/withdraw_test.go
Ref: https://github.com/PundiAi/fx-core/pull/792
=> test: remove duplicate test cases

x/crosschain/keeper/bridge_call_in.go, x/crosschain/keeper/keeper.go, x/crosschain/keeper/outgoing_tx.go
Ref: https://github.com/PundiAi/fx-core/pull/840
=> fix: grammar improvements

solidity/linter.sh
Ref: https://github.com/PundiAi/fx-core/pull/850
=> chore: improve linter scripts for better code analysis

solidity/contracts/token/PundiAIFX.sol, solidity/test/pundiaifx.ts
Ref: https://github.com/PundiAi/fx-core/pull/893
=> fix: correct parameter name in burn method

contract/crosschain.go
Ref: https://github.com/PundiAi/fx-core/pull/898
=> fix: validate chain arguments to prevent errors

app/upgrades/v8/upgrade.go
Ref: https://github.com/PundiAi/fx-core/pull/914
=> fix: improve error handling in metadata display migration

contract/contract_test.go, x/crosschain/keeper/bridge_fee_test.go
Ref: https://github.com/PundiAi/fx-core/pull/927
=> test: add unit test for UnpackRevertError function

app/upgrades/v8/feegrant.go, app/upgrades/v8/feegrant_test.go
Ref: https://github.com/PundiAi/fx-core/pull/936
=> refactor: avoid modifying allowanceList while iterating over it

app/upgrade_test.go
Ref: https://github.com/PundiAi/fx-core/pull/957
=> fix: make format

x/ibc/middleware/keeper/keeper_test.go, x/ibc/middleware/keeper/relay_test.go
Ref: https://github.com/PundiAi/fx-core/pull/969
=> fix: correct the implementation for test

.github/workflows/npm.yml
Ref: https://github.com/PundiAi/fx-core/pull/967
=> chore: set NODE_AUTH_TOKEN env in github action

x/crosschain/keeper/oracle_set_test.go
Ref: https://github.com/PundiAi/fx-core/pull/1016
=> fix: incorrect variable in height assertion

app/upgrades/v8/crosschain.go
Ref: https://github.com/PundiAi/fx-core/pull/1021
=> fix: add caching mechanism for transaction handling

x/crosschain/keeper/bridge_token_test.go
Ref: https://github.com/PundiAi/fx-core/pull/1022
=> fix: add origin tokens for multiple chains

Dockerfile.cosmovisor, Dockerfile.cosmovisor-lite
Co-authored-by: nulnut <151493716+nulnut@users.noreply.github.com>
(cherry picked from commit f9ed57ac3007b93dded801cdd781fd7f5ce2aa79)
=> ci(docker): update cosmovisor dockerfile (#1037)

scripts/linter.sh
Ref: https://github.com/PundiAi/fx-core/pull/1045
=> chore: update linter scripts rules

scripts/linter.sh, server/start.go
Ref: https://github.com/PundiAi/fx-core/pull/1065
=> chore: ignore lint
